# A docker compose file for running Keycloak
#
# Note that the behaviour on Windows is different from that on Linux. For example, under Linux,
# the default DB is PostgreSQL, and if you don't have it, it does not run (and does not warn you either).
# So you need to explicitly specify the database, e.g. H2.
#
# Additionally, under Linux, https access is required. You can circumvent that temporarily by accessing the
# container (below, I've set the container's name to kc).
# See also: https://stackoverflow.com/a/49894254/319711
#
# docker exec -it kc bash
# cd keycloak/bin
# ./kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin
# Changing ssl settings on the realm:
# ./kcadm.sh update realms/master -s sslRequired=NONE

---
version: "3"
services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: kc
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${ADMIN_PWD}
    expose:
      - 8080
    # command:
    #   - "-b 0.0.0.0"
    #   - "-Dkeycloak.import=/opt/jboss/keycloak/l3-realm.json"
    ports:
      - "8765:8080"
    volumes:
      - ./l3-realm.json:/opt/jboss/keycloak/l3-realm.json

# https://github.com/tomav/docker-mailserver
#   mail:
#     image: tvial/docker-mailserver:latest
#     hostname: mail
#     domainname: driver-testbed.eu
#     container_name: mail
#     ports:
#       - "25:25"
#       - "143:143"
#       - "587:587"
#       - "993:993"
#     volumes:
#       - maildata:/var/mail
#       - mailstate:/var/mail-state
#       - maillogs:/var/log/mail
#       - ./config/:/tmp/docker-mailserver/
#     env_file:
#       - .env
#       - env-mailserver
#     cap_add:
#       - NET_ADMIN
#       - SYS_PTRACE
#     restart: always
# volumes:
#   maildata:
#     driver: local
#   mailstate:
#     driver: local
#   maillogs:
#     driver: local
# docker exec -it kc keycloak/bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.realmName=l3 -Dkeycloak.migration.usersExportStrategy=REALM_FILE -Dkeycloak.migration.file=./l3.json
